<?php

$params = array_merge(
        require __DIR__ . '/../../common/config/params.php',
        require __DIR__ . '/../../common/config/params-local.php',
        require __DIR__ . '/params.php',
        require __DIR__ . '/params-local.php'
);

return [
    'id' => 'app-api',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'api\controllers',
    'modules' => [
        'lenguaje' => [
            'class' => 'backend\modules\admin\Localidades',
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],
        'session' => ['name' => 'advanced-api'],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'trace', 'info'],
                    'categories' => ['application', 'yii\db\*', 'yii\web\HttpException:*', 'yii\base\ErrorException:*']
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => false,
            'showScriptName' => false,
            'rules' => [
                ///  SE DECLARA EL CONTROLADOR CUANDO EL METODO ES TIPO CREATE
                ['class' => 'yii\rest\UrlRule', 'controller' => 'items', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientes', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'user', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'usuario', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'persona', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'login', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'localidad', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pass', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'resetear', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'configuser', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'almacenes', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'vendedores', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'listaprecios', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'listaunidades', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pedido', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'lote', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'tipocambio', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'solicitudregistro', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'sap', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'productosalmacenes', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'productosprecios', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientessucursales', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'vendedores', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientesgrupos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'buscarci', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'productosalprun', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'unidadesmedida', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'condicionpago', 'pluralize' => false],
                //['class' => 'yii\rest\UrlRule', 'controller' => 'territorios', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'descuento', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientesimport', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientesimportdos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pagos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'leyendas', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'facturas', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'motivoanulacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'cuentascontables', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'image', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'numeracion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientescontacto', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'reportefacturas', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'productosalternativos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'cambiodivisa', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'series', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'cierre', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'documentos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'lbcc', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'entrega', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'documentcancel', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'facturasapp', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'centrocostos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'cnfseries', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pedidosexport', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'lbccexport', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'documentoscloneexport', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'changecantdetalle', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'tipocambiomovil', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'cambiodivisasmovil', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'sincronizacionmiddleware', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'registerequipo', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'tipopapel', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'conciliacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'seriesproductos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'lotesproductos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'geolocalizacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'documentohtml', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'autorizacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pedidosmovil', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientesmovil', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'gestionbancos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'reportessap', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'pagosmoviles', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'report', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'facturasappmovil', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'clientesearchmovil', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'arqueocaja', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'reimpresion', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'anulacion', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'documentosmovilsap', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'documentosmovilsapdetalle', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'detallesmovilsap', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'visitas', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'grupoclientedocificacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'grupoproductodocificacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'bonificacionca', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'bonificacionde1', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'bonificacionde2', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'configuracionesgenerales', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'poligono', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/condicionpago', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/pagosmoviles', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/pedidosmovil', 'pluralize' => false],
				['class' => 'yii\rest\UrlRule', 'controller' => 'v2/cancelarpago', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/cancelardocumento', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/grupospercepciones', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/clientespercepciones', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/gestionsap', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/almacenpercepciones', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/servicioventa', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/configuracionimpuestos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/tipooperacion', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/precioventaunit', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/tipoafectacionigv', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/transportista', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/indicadoresimpuestos', 'pluralize' => false],
                ['class' => 'yii\rest\UrlRule', 'controller' => 'v2/evidencias', 'pluralize' => false],
            ]
        ],
    ],
    'params' => $params,
];
